<?php

//https://www.php.net/manual/en/session.security.ini.php

if (!isset($_SESSION)) {
    //Allow access to the session ID cookie only when the protocol is HTTPS. If a website is only accessible via HTTPS, it should enable this setting.
    //CHANGE WHEN DEPLOYING
    ini_set('session.cookie_secure', 0);
    //Make sure that cookies can only be accessed in http requests (not JS), which prevents CSRF
    ini_set('session.cookie_httponly', 1);
    //Only use cookies for session ID management when it is possible. Most applications should use a cookie for the session ID.
    //If session.use_only_cookies=Off, the session module will use the session ID values set by GET/POST/URL provided the session ID cookie is uninitialized.
    ini_set('session.use_only_cookies', 1);
    //This prevents the session module to use an uninitialized session ID. It accepts valid session IDs generated by the session module. It rejects any session ID supplied by users.
    //session.use_strict_mode can prevent an attacker initialized session ID of being used.
    ini_set('session.use_strict_mode', 1);
    session_start();
}